- cli.js
```sh
$ node cli --version # 0.8.0
$ node cli --help
cli
Options:
--why, -w      Show package content                                  [boolean]
--babili       Use babili minifier                                   [boolean]
--version, -v  Show version number                                   [boolean]
--help, -h     Show help                                             [boolean]
Size Limit will read size-limit section from package.json.
Configuration example:
"size-limit": [
{
"path": "index.js",
"limit": "9 KB",
"babili": true
}
]
```
> Add babili flag to documentation and fix typo

- cli.js
I had problem with Webpack Bundle Analyzer start after ```npx size-limit --why``` command.
In ```cli.js``` file I described it.
> Error with Webpack Bundle Analyzer start

- cli.js
- index.js
- test/cli.test.js
- test/fixtures/config/index.js
- test/fixtures/config/package.json
- test/fixtures/config/webpack.config.js
In attempt to address https://github.com/ai/size-limit/issues/16, I have implemented a new `--config` flag that takes a custom webpack config, and bundles the output with that instead of the one predefined [here](https://github.com/ai/size-limit/blob/master/index.js#L32-L78). Here is an example of the new functionality on a private repo of mine:
```
➜  demo git:(size) npm run size
npm info it worked if it ends with ok
npm info using npm@3.10.10
npm info using node@v6.11.2
npm info lifecycle demo@3.2.2~presize: demo@3.2.2
npm info lifecycle demo@3.2.2~size: demo@3.2.2
> demo@3.2.2 size /Users/smehta/github.com/SivanMehta/react-demo
> size-limit --config webpack.config.js
Package size: 303.86 KB
With given webpack configuration
npm info lifecycle demo@3.2.2~postsize: demo@3.2.2
npm info ok …
```
> Support custom webpack.config.js

- README.md
- cli.js
- package.json
- test/cli.test.js
- test/fixtures/with-file-config/.size-limit
- test/fixtures/with-file-config/index.js
- test/fixtures/with-file-config/package.json
- test/fixtures/wrong-file-config/.size-limit
- test/fixtures/wrong-file-config/index.js
- test/fixtures/wrong-file-config/package.json
- yarn.lock
Do I need to write more tests?
> Added config file support

- appveyor.yml
Node.js 4 was removed only for Travis in b7276b7e0e3cd154e6d3e3aeef4fc7d5c37d849d and is failing the Appveyor builds
> Remove Node.js 4 from Appveyor testing

- .travis.yml
Some time ago `stable` was deprecated in favor of `node` identifier
> Add correct latest stable version

- index.js
- test/cli.test.js
- test/index.test.js
Currently not gziped empty projects shows 267 bytes. It's because you used only one constant for this.
> Distinct minified and gziped empty sizes

- index.js
- package.json
- test/cli.test.js
- test/index.test.js
- yarn.lock
Current results are a kind of lie since uglify is applied twice. Webpack by default adds uglify and define plugin with `production` string
> Remove duplicated uglify and define plugin

- README.md
- cli.js
- index.js
- test/index.test.js
In my opinion both bundle and gzip results are important since there is also a cost of javascript parsing. This will let to bundle the code only once and have more pretty result. Currently I got this
```
esm/index.js
Package size: 29.8 KB
esm/index.js
Package size: 9.34 KB
Size limit:   9.4 KB
```
In the next PR I'm gonna improve render in cli
> Return from getSize both bundle and gzip results

- cli.js
- test/cli.test.js
- test/fixtures/array-path/index1.js
- test/fixtures/array-path/index2.js
- test/fixtures/array-path/package.json
- moved size renderer into pure function
- fixed `index1.js,index2.js` size name because of implicit casting array to string (types are really good here)
- removed a few unused props (and here)
- merged a few `then` chains because async operations are not required between them
- prevented parsing number with `bytes.parse` (and here)
> Refactor render and fix array path output

- cli.js
Next.js 6 now generates a vendor bundle with a dynamic filename. I'm looking for a way to handle this change. If you are happy with this change, I can update the documentation.
https://github.com/davidtheclark/cosmiconfig#searchplaces
> Allow the usage of dynamic configuration

- index.js
- package.json
- yarn.lock
Size limit is throwing an error on my project when I upgrade css-loader to ^2.0.1
Seems minimize was already removed as an option in css-loader in [v1.0.0](https://github.com/webpack-contrib/css-loader/releases/tag/v1.0.0), but only in v2.0.0 did they add verification of illegal parameters.
Thanks!
> fix(css-loader): remove minimize option

- README.md
Fixes #85.
Anyway, @ai, do you know, maybe there is a way to subtract size of style-loader or even don't add it to the bundle? It looks like an annoying side effect that shouldn't exist in a such library.
> Add a tip about CSS files' size calculation

- README.md
Remove fixed `height` props from images to make its look ok on small screens
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
> Fixes height of images in readme

- index.js
- package.json
- test/cli.test.js
- test/fixtures/peer/index.js
- test/fixtures/peer/package.json
- test/index.test.js
- yarn.lock
Addresses the problem raised in #121 - having `react` as `peerDep` would add any `react-*` packages to the ignore list, which is almost all packages :)
Restore old RegExp based check, keeping the new `externalize` behavior
I've added `redux-thunk`, as long it matches the problem, and configured test to handle it.
> Greedy ignore pattern, fixes #121

- cli-body.js
- index.js
Without this option `--why` is almost useless for tree-shakable (and thus _concatenatable_) modules - see #117.
In the same time - disabling concatenation greatly affect result bundle size, thus it should be optional.
- Added a new CLI option
- Added a new API option with _reversed_ sense, to keep all existing customers untouched.
It will require the usage of ESM. While this could be a good thing to test, I am not ready to do it as my first-time contribution - I've tested manually.
> Control over webpack ModuleConcatenationPlugin, fixes #117

- packages/size-limit/load-plugins.js
Presets are looked for starting from the current folder (the current working directory of the process) and going down to the root to be sure of primary using the ones from local `node_modules`.
> Getting plugins from local node_modules

- packages/size-limit/create-help.js
- packages/size-limit/test/__snapshots__/run.test.js.snap
Just a small spelling fix:
> All plugins and presets already **contain** it as own dependency
I was actually thinking about a more informative message:
> As of __<version_number>__ having `size-limit` as a dependency is no longer required.
> You can safely remove it from your package.json since all plugins and presets already contain it as a dependency.
> Read more: https://github.com/ai/size-limit#usage
Let me know what you think.
> CLI message: use a plural form of the verb "contain" 

- packages/size-limit/calc.js
When size-limit checks the size for 16 files, these warnings appear in the log (on the local machine and CI)
```
yarn run v1.19.2
$ yarn size-limit
$ /home/circleci/size-limit-test/node_modules/.bin/size-limit
(node:99) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added to [process]. Use emitter.setMaxListeners() to increase limit
(node:99) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added to [process]. Use emitter.setMaxListeners() to increase limit
(node:99) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGTERM listeners added to [process]. Use emitter.setMaxListeners() to increase limit
(node:99) MaxListenersExceededWarning: Possible EventEmitter memory leak …
```
> Fix MaxListenersExceededWarning

- packages/size-limit/test/__snapshots__/run.test.js.snap
- packages/webpack/get-config.js
- packages/webpack/package.json
- yarn.lock
before:
```
[~/site-new]$ yarn size                                                                                                                                                      *[yarn2][ruby-2.6.1]
WARN  You can remove size-limit dependency
All plugins and presets already contain it as own dependency
yarn remove size-limit
ERROR  Error:
ERROR in multi ./build/app.2dc4b36696c9586571f9.css
Module not found: Error: Can't resolve 'style-loader' in '/Users/pavel/site-new'
@ multi ./build/app.2dc4b36696c9586571f9.css index[0]
at /Users/pavel/site-new/.yarn/cache/@size-limit-webpack-npm-3.0.0-6b1f9f999d-1.zip/node_modules/@size-limit/webpack/run-webpack.js:8:23
at finalCallback (/Users/pavel/site-new/.yarn/cache/webpack-npm-4.41.5-ec6f53e9d3-1.zip/node_modules/webpack/lib/Compiler.js:257: …
```
> @size-limit/webpack: add pnp support

- README.md
This PR adds [size-limit-action](https://github.com/andresz1/size-limit-action) to `README.md`. I'm not sure if adding the integration steps make sense or if would be nice to add a screenshot.
Let me know what you think! @ai 😉Any suggestion will be more than welcome
> Add size-limit-action to README.md

- packages/size-limit/test/run.test.js
Reference to: https://github.com/ai/size-limit/issues/164
Regex demo: https://regex101.com/r/mr7kpc/1
before:
```
[~/size-limit]$ yarn test                                                                                                                                           *[pp-macos-specs][ruby-2.6.1]
yarn run v1.22.4
$ jest-ci --coverage --forceExit && eslint-ci . && yarn spell
PASS  packages/size-limit/test/bin.test.js
PASS  packages/time/test/index.test.js
PASS  packages/size-limit/test/size-limit-error.test.js
PASS  packages/file/test/index.test.js
PASS  packages/time/test/cache.test.js
PASS  packages/size-limit/test/create-reporter.test.js
PASS  packages/time/test/ci.test.js
PASS  packages/dual-publish/test/index.test.js
PASS  packages/size-limit/test/get-config.test.js
PASS …
```
> Fix spec when running on macOS

- packages/size-limit/create-help.js
- packages/size-limit/test/__snapshots__/run.test.js.snap
It's easier to read this way, and more clear to what case which command corresponds
> Add newlines between migration guide variants

- packages/size-limit/calc.js
related to this issue: https://github.com/ai/size-limit/issues/184
these fixes:
#150
#149
stopped working in version 4.2 (https://github.com/ai/size-limit/commit/f3f44dc94270d4daf54493fbb0662791ffda1279#diff-a1a166c1c48dcde0ef1338a880cb707aR2)
Currently always exists +1 listener
[4.5.2](https://github.com/pustovalov/size-limit-test/tree/4.5.2)
```
[~/dev/oss/size-limit-test]$ yarn size                                                                                                                                        *[4.5.2]
yarn run v1.22.4
$ yarn size-limit
$ /Users/pavel/dev/oss/size-limit-test/node_modules/.bin/size-limit
Count of files: 16
⠋ Running JS in headless Chrome(node:88579) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 17 SIGINT listeners added …
```
> Improvement for setMaxListeners

- packages/size-limit/parse-args.js
- packages/size-limit/size-limit-error.js
- packages/size-limit/test/__snapshots__/run.test.js.snap
- packages/size-limit/test/run.test.js
I made this PR, because of two reasons. The first one is the command
```
size-limit --save-bundle
```
does't save bundle and trigger any errors. And the second one is
```
size-limit --save-bundle --clean-dir
```
saves bundle to `--clean-dir` folder.
> add check for missing DIR parameter of save-bundle argument

- packages/size-limit/create-reporter.js
- packages/size-limit/get-config.js
- packages/size-limit/parse-args.js
- packages/size-limit/test/__snapshots__/create-reporter.test.js.snap
- packages/size-limit/test/create-reporter.test.js
- packages/size-limit/test/get-config.test.js
The output can be very long if you have a lot of bundles that you're checking. The `--hide-passed` option will only output check failures.
> Add `--hide-passed` flag to only output failed checks

- packages/size-limit/create-reporter.js
- packages/size-limit/test/__snapshots__/create-reporter.test.js.snap
- packages/size-limit/test/create-reporter.test.js
- packages/webpack/get-config.js
- packages/webpack/test/index.test.js
This PR utilises `BundleAnalyzerPlugin` to emit Webpack stats file alongside with the bundle when `--save-bundle` is used. It comes handy when one wants to inspect the bundle as [Webpack’s analyser](http://webpack.github.io/analyse) could be used to find out more about reasons why some dependency was included.
> Emit Webpack stats JSON file

- packages/size-limit/load-plugins.js
- packages/size-limit/run.js
- packages/size-limit/test/__snapshots__/run.test.js.snap
- packages/size-limit/test/fixtures/nested/package.json
- packages/size-limit/test/fixtures/nested/package/package.json
- packages/size-limit/test/run.test.js
Fixes #153 
I do not use `require.resolve`, cause too much logic inside relied on `process.cwd`, instead I decided to find plugins in parent `package.json` dependencies.
> Look up for plugins in parent package.json

- README.md
- package.json
- packages/preset-big-lib/README.md
- packages/preset-small-lib/README.md
- packages/size-limit/create-help.js
- packages/size-limit/create-reporter.js
- packages/size-limit/get-config.js
- packages/size-limit/package.json
- packages/size-limit/size-limit-error.js
- packages/size-limit/test/__snapshots__/create-reporter.test.js.snap
- packages/size-limit/test/__snapshots__/run.test.js.snap
- packages/size-limit/test/create-reporter.test.js
- packages/size-limit/test/fixtures/brotli-with-gzip/package.json
- packages/size-limit/test/fixtures/brotli-without-webpack/package.json
- packages/size-limit/test/fixtures/brotli/package.json
- packages/size-limit/test/fixtures/file-not-found-json-config/.size-limit.json
- packages/size-limit/test/fixtures/file-not-found/package.json
- packages/size-limit/test/fixtures/globby/package.json
- packages/size-limit/test/fixtures/max-listeners/package.json
- packages/size-limit/test/fixtures/nested/package/package.json
- packages/size-limit/test/fixtures/npm-with-config-without-dev/package.json
- packages/size-limit/test/fixtures/simple/package.json
- packages/size-limit/test/fixtures/warn/package.json
- packages/size-limit/test/fixtures/yarn-without-dev-dep/package.json
- packages/size-limit/test/get-config.test.js
- yarn.lock
I've replaced the [`bytes`](https://www.npmjs.com/package/bytes) packages with [`bytes-iec`](https://www.npmjs.com/package/bytes-iec) which uses the correct units.
I also went through the project and replaced usages of `KB` with `kB` where appropriate.
This fixes #218.
> Fix size units

- packages/size-limit/test/__snapshots__/run.test.js.snap
- packages/webpack/package.json
- yarn.lock
Fixes #225 
Currently when running `npm audit` or `yarn audit` there are warnings related to the following moderate severity security, relating to particular versions of the `postcss` plugin:
https://www.npmjs.com/advisories/1693
This PR bumps the versions of the `css-loader` and `optimize-css-assets-webpack-plugin` dependencies in the package.json of `packages/webpack` to fix these issues.
Tests were ran and fixed.
> bumped dependencies to fix npm/yarn audit warnings

- README.md
- package.json
- packages/size-limit/get-config.js
- packages/webpack/index.js
- packages/webpack/test/fixtures/referencingAlias.js
- packages/webpack/test/index.test.js
So, we want to use this for `@reduxjs/toolkit` which will have multiple entry points from the next version that reference each other, so we need to add the `NormalModuleReplacementPlugin`.
Rather than creating a bunch of fixed webpack configs that don't work with `--why`, this allows to just do some last-minute changes to the webpack config.
Hope you'll accept this - it would be a great help for us :slightly_smiling_face: 
Usage in our case looks like this:
```js
function withRtkPath(path) {
return (config) => {
const rtkPath = path.replace(
/(query\/rtk-query|query\/react\/rtk-query-react)/,
'redux-toolkit'
)
config.plugins.push(
new webpack.NormalModuleReplacementPlugin(
/@reduxjs\/toolkit/,
join(__dirname, rtkPath)
)
)
return config
}
}
// ...
{
name: `createApi (${path})`,
path, …
```
> add `modifyWebpackConfig` config option

- README.md
- packages/size-limit/get-config.js
ES Modules cannot be required. This prevents ES Module projects with `"type": "module"` in their package.json from using a .size-limit.js file for config, which restricts the use of the modifyWebpackConfig option introduced in #226. Allowing for a .cjs extension for the config file solves this.
Below is the error message shown after running `size-limit` with a `.size-limit.js` config file in a repo with `"type": "module"`
```js
// .size-limit.js
module.exports = [
{
path: 'index.js'
}
];
```
```bash
$ npx size-limit
ERROR  Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /path/to/lib/.size-limit.js
require() of ES modules is not supported.
require() of /path/to/lib/.size-limit.js from /path/to/lib/node_modules/lilconfig/dist/index.js is an ES module file as it is a .js file …
```
> Add support for .size-limit.cjs config file

- packages/size-limit/load-plugins.js
Currently if you install size-limit presets in your as optional dependency (mainly useful not to download chromium if you don't need to in your CI using `--no-optional`) then size-limit will not find plugins.
This PR adds this feature.
> Add optional dependencies support

- packages/size-limit/test/__snapshots__/run.test.js.snap
- packages/size-limit/test/get-config.test.js
- packages/size-limit/test/index.test.js
- packages/webpack/get-config.js
- packages/webpack/index.js
- packages/webpack/package.json
- packages/webpack/test/index.test.js
- yarn.lock
Since more projects like Next.js are moving to webpack 5 by default, I've had another go at https://github.com/ai/size-limit/issues/205. Moving to webpack 5 also helps with https://github.com/ai/size-limit/issues/232 since webpack 5 itself has fewer dependencies.
I've used the previous PR https://github.com/ai/size-limit/pull/206 as a basis.
I've struggled with updating the expected bundle sizes in tests as I could not understand exactly how the constants inn https://github.com/ai/size-limit/blob/86fe4662d0f90681127ec78759c720dab2f7c30a/packages/webpack/index.js#L12 were computed.
With webpack 5, the outputs seem to be sometimes larger and sometimes smaller.
Also I am not sure how to check that the bundle analyzer works correctly.
The previous blocker was webpack-bundle-analyzer not …
> Update to webpack v5

- README.md
to use latest version, `v1.0.0` is outdated
https://github.com/andresz1/size-limit-action/issues/68#issuecomment-979479985
> docs: fix action version in workflow example

- README.md
- packages/esbuild/test/index.test.js
- packages/size-limit/process-import.js
I wanted to allow importing all ESM modules in one by adding support for `import: '*'`
> Add support for wildcard importing ESM

- README.md
I've fixed a few minor things in the README. Here is a list:
1. Unnecessary double newlines.
2. English error:
"Third-party plugins and presets named start***ING*** with `size-limit-` are also supported"
3. List went 1, 2, 3, 4, 6, 7, 8, 9. Bumped back 6, 7, 8, and 9. There are 8 items in the list.
4. In markdown when displaying shell commands, the `$` should only be present when the result of the command is displayed right below within the same block. If it's just the command alone, the `$` should be omitted.
> fix(README): typos and markdown issues

- packages/size-limit/run.js
Prevent messages like: `✔ Adding to empty esbuild project` while enabled silent mode
> fix: prevent spinner output while --silent

- packages/webpack-why/package.json
Add webpack to peer-deps / Cascade the requirement from @statoscope/webpack-plugin.
Same range as statoscope 
https://github.com/statoscope/statoscope/blob/42ec9ffff9688d6ec55abec9e05922b0d45e241c/packages/webpack-plugin/package.json#L37-L39
Helps to keep the install clean from warnings. 
```
➤ YN0000: ┌ Resolution step
➤ YN0002: │ @size-limit/webpack-why@npm:8.1.2 [7d865] doesn't provide webpack (p8195f), requested by @statoscope/webpack-plugin
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 0s 259ms
```
BTW. Thanks for size-limit :pray:
> @size-limit/webpack-why: add webpack to peers

- pnpm-lock.yaml
Still no clue where the peer dependency requirement comes from, I don't see it defined in either `size-limit-node-esbuild` or `size-limit` itself.
Now users could update to `tslib` 2.5.3 at least to satisfy and match the dependency requirement.
Closes https://github.com/ai/size-limit/issues/326
***
- re-install `size-limit-node-esbuild` to refresh `tslib` from 2.5.0 to 2.5.3
> chore: loose strictness of peer dependency requirement of `tslib`

- README.md
- packages/esbuild-why/index.js
- packages/esbuild-why/package.json
- packages/esbuild-why/test/index.test.js
- pnpm-lock.yaml
This small change remove the need to manually open generated esbuild reports
> @size-limit/esbuild-why: Automatically open esbuild reports 

- fixtures/zero-esbuild/package.json
- package.json
- packages/size-limit/test/load-plugins.test.js
- packages/webpack-css/index.js
- pnpm-lock.yaml
Good day! Thank you very much for this amazing tool!
In our project we are using `size-limit` with` @size-limit/webpack-css` plugin and with latest version `v10.0.1` we are having an issue and see this error running `size-limit`.
```
ReferenceError: require is not defined in ES module scope, you can use import instead\nThis file is being treated as an ES module because it has a '.js' file extension
```
<details>
<summary>The whole error</summary>
```
{
"error": "ReferenceError: require is not defined in ES module scope, you can use import instead\nThis file is being treated as an ES module because it has a '.js' file extension and '/Users/andrey.medvedev/src/experiment
/size-limit-experiment/node_modules/@size-limit/webpack-css/package.json' contains \"type\": \"module\". To treat it as a …
```
> fix(@size-limit/webpack-css  v10.0.1 ): require is not defined in ES module scope when running size-limit

- packages/webpack/index.js
- packages/webpack/test/fixtures/cjs/webpack-func.config.js
- packages/webpack/test/fixtures/cjs/webpack-promise.config.js
- packages/webpack/test/fixtures/esm/webpack-func.config.js
- packages/webpack/test/fixtures/esm/webpack-promise.config.js
- packages/webpack/test/index.test.js
Fixes issue #315 
The `loadConfig` function is deliberately made async, so:
1. If the custom webpack config function returns a promise — it is resolved and the result is passed to webpack.
2. If the custom webpack config is an object, or it is a synchronous function — the await statement has no effect and the resulting object is passed as is.
> Add support for webpack config defined as function

- packages/size-limit/load-plugins.js
> fix: use dynamic `import` directly without `require.resolve`

- fixtures/js-config-file-with-type-module/.size-limit.js
- fixtures/js-config-file-with-type-module/index.js
- fixtures/js-config-file-with-type-module/package.json
- fixtures/js-config-file/.size-limit.js
- fixtures/js-config-file/index.js
- fixtures/js-config-file/package.json
- fixtures/mjs-config-file/.size-limit.mjs
- fixtures/mjs-config-file/index.js
- fixtures/mjs-config-file/package.json
- packages/size-limit/get-config.js
- packages/size-limit/package.json
- packages/size-limit/test/get-config.test.js
- pnpm-lock.yaml
> Add support `.mjs` config files

- packages/webpack-why/index.js
An error `TypeError: StatoscopeWebpackPlugin is not a constructor` occurs if the module does not export as default.
@ai Hello, I wanted to bring to your attention an issue I've found while utilizing the `@size-limit/webpack-why` package. Since I got an error message (`StatoscopeWebpackPlugin is not a constructor`), I have consulted with the [official documentation](https://github.com/statoscope/statoscope/tree/master/packages/webpack-plugin). They advised that the class should be imported using the default export.
I have submitted a PR addressing this matter and would greatly appreciate it if you could take a moment to review the proposed changes. Your feedback would be invaluable.
> Fix StatoscopeWebpackPlugin import to support default export

- packages/webpack-why/index.js
> Fix ensure compatibility with ES and CommonJS module systems for StatoscopeWebpackPlugin

- packages/size-limit/get-config.js
> Fix config file path resolution on windows

- packages/esbuild/index.js
- packages/esbuild/test/fixtures/esm/nonjs.js
- packages/esbuild/test/fixtures/esm/style.css
- packages/esbuild/test/index.test.js
- packages/size-limit/size-limit-error.js
- packages/size-limit/test/__snapshots__/size-limit-error.test.js.snap
`parse('index.css').name` and `parse('index.js').name` prodiuces the same `index` key, which overwrites one of the entries. 
Use `base` to prevent conflicts and use `index.js`/`index.css` as the keys.
Fixes #360
> Support css content in esbuild plugin

- packages/size-limit/index.d.ts
> Fix type of `plugins` parameter to be an array of functions

- packages/size-limit/package.json
- pnpm-lock.yaml
upgrades chokidar to v4 which drops 11 dependencies and improves it's types.
> chore(deps): bump chokidar to v4

- packages/size-limit/get-config.js
- packages/size-limit/package.json
- pnpm-lock.yaml
> Update `jiti` usage to use `jiti.import()`

- README.md
- packages/size-limit/create-reporter.js
- packages/size-limit/get-config.js
- packages/size-limit/test/__snapshots__/create-reporter.test.js.snap
- packages/size-limit/test/create-reporter.test.js
Closed https://github.com/ai/size-limit/issues/350
> add `message` option

- packages/size-limit/create-reporter.js
- packages/size-limit/test/__snapshots__/create-reporter.test.js.snap
- packages/size-limit/test/__snapshots__/run.test.js.snap
The simpler solution is to use `process.stdout.moveCursor()` and `process.stdout.clearLine()` directly. However, i[f TTY is not available we can not use those methods](https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000645510/comments/115000530624) and consuming `readline` is a better-supported solution to do that.
Resolves #363
> fix: remove extra blank line in terminal when output is empty

- README.md
- fixtures/config-file-from-arg/index.js
- fixtures/config-file-from-arg/package.json
- fixtures/config-file-from-arg/src/configs/my-size-limit.config.js
- fixtures/config-file-from-arg/src/main.js
- packages/size-limit/get-config.js
- packages/size-limit/parse-args.js
- packages/size-limit/test/__snapshots__/run.test.js.snap
- packages/size-limit/test/get-config.test.js
- packages/size-limit/test/run.test.js
This PR introduces a new `--config` argument to specify a custom path to the `size-limit` configuration file when running CLI.
Resolves #367
Further enhancement:
- add validation for config extension to throw a custom size-limit error. Currently, it will be `Error: No loader specified for extension ".extension"`;
- catch an error if there is no such file or directory from the parameter to throw a custom size-limit error. Currently, it will be `Error: no such file or directory...`.
> feat: implement new --config arg to specify a custom path to configuration file when running CLI
