ai/size-limit

README.md
=> Add Material-UI

README.md
=> update usage example in readme

cli.js
I noticed the typo in this error message locally and thought I should send a PR to fix it.
Thanks for the great library!
=> Fixes a small typo

CHANGELOG.md, index.js, test/cli.test.js, test/index.test.js
Fixes https://github.com/ai/size-limit/issues/68.
I rushed this fix and haven't tested it much.
=> Fix ignore option.

README.md
add information how to add this library via yarn package manager
=> add yarn to readme.md

test/fixtures/markdown/fixture.md, test/fixtures/markdown/index.js, test/fixtures/markdown/package.json, test/index.test.js
Добавил тест который нужен для #81
=> Add markdown test

index.js
Added mark down to the list for file loading.
=> Added markdown to static file list

README.md
* Improve English wording
* Remove “You can” to simplify wording (reference in Russian: http://maximilyahov.ru/blog/all/modality/)
Please let me know if the updated project description lost any important piece of meaning.
=> Improve the project description

cli-body.js, package.json, test/cli.test.js, test/fixtures/main-no-extension/app.js, test/fixtures/main-no-extension/package.json
closes #106
Added `yarn watch` to run `jest` in watch mode
=> fix: support extensionless main field

README.md
- Added explanation of the difference between “big” and “small” presets.
- Minor grammar tweaks here and there.
=> Readme tweaks: difference between big and small

CHANGELOG.md
=> Update changelog with v2 migration guide

packages/size-limit/calc.js
<details>
<summary>Size Limit Config Checks</summary>
```
[
{
path: [
'/packs-test/vendors~253ae210-9029a83ef8693c06b7ad.js',
'/packs-test/vendors~31ecd969-71462969e232129bb5fb.js',
'/packs-test/vendors~64dbdf6f-0871dc7a2be125e1562d.js',
'/packs-test/vendors~7d359b94-06e6b2fb45a4ff2b7001.js'
],
limit: '705 KB',
name: 'public/packs-test/vendors~253ae210-9029a83ef8693c06b7ad.js, public/packs-test/vendors~31ecd969-71462969e232129bb5fb.js, public/packs-test/vendors~64dbdf6f-0871dc7a2be125e1562d.js, public/packs-test/vendors~7d359b94-06e6b2fb45a4ff2b7001.js',
sizeLimit: 721920,
size: 762789
},
{
path: [
'/packs-test/lite-common~253ae210-a605f1e69a7e734a2f33.js',
'/packs-test/lite-common~678f84af-3634e3caaeabac6e681a.js'
],
limit: '500 KB',
name: …
```
=> Improvement for setMaxListeners

packages/size-limit/get-config.js, packages/webpack/get-config.js, packages/webpack/package.json, packages/webpack/test/fixtures/module.js, packages/webpack/test/index.test.js, yarn.lock
This option allows specifying a specific exported object to be imported
from the configured path, allowing testing for tree shaking.
Closes ~~https://github.com/ai/size-limit/issues/161~~ https://github.com/ai/size-limit/issues/111
TODOs:
=> Add import option to check config

package.json
Frozen spec:
https://github.com/ai/size-limit/blob/master/packages/size-limit/test/run.test.js#L206
```
[~/size-limit]$ yarn jest packages/size-limit/test/run.test.js --detectOpenHandles                                                                                           *[master][ruby-2.6.1]
```
```
yarn run v1.22.4
$ /Users/pavel/size-limit/node_modules/.bin/jest packages/size-limit/test/run.test.js --detectOpenHandles
PASS  packages/size-limit/test/run.test.js
✓ works in integration test in watch (1148ms)
○ skipped shows version
Test Suites: 1 passed, 1 total
Tests:       37 skipped, 1 passed, 38 total
Snapshots:   1 passed, 1 total
Time:        1.631s, estimated 2s
Ran all test suites matching /packages\/size-limit\/test\/run.test.js/i.
.........
```
```
[~/size-limit]$ yarn jest …
```
=> Try to fix frozen spec

packages/size-limit/calc.js, packages/size-limit/create-help.js, packages/size-limit/get-config.js, packages/size-limit/parse-args.js, packages/size-limit/size-limit-error.js, packages/size-limit/test/__snapshots__/run.test.js.snap, packages/size-limit/test/get-config.test.js, packages/size-limit/test/run.test.js, packages/webpack/index.js, packages/webpack/test/index.test.js
Closes https://github.com/ai/size-limit/issues/179
=> add --clean-dir argument to remove bundle dir/ before each call

packages/size-limit/create-reporter.js, packages/size-limit/test/__snapshots__/create-reporter.test.js.snap, packages/size-limit/test/create-reporter.test.js
=> Fixed note while using file plugin with enabled gzip

package.json, packages/dual-publish/index.js, packages/dual-publish/test/index.test.js, packages/file/index.js, packages/file/test/index.test.js, packages/size-limit/calc.js, packages/size-limit/create-reporter.js, packages/size-limit/get-config.js, packages/size-limit/index.js, packages/size-limit/test/__snapshots__/run.test.js.snap, packages/size-limit/test/fixtures/file-not-found-json-config/.size-limit.json, packages/size-limit/test/fixtures/file-not-found-json-config/package.json, packages/size-limit/test/fixtures/file-not-found/package.json, packages/size-limit/test/get-config.test.js, packages/size-limit/test/run.test.js, packages/time/index.js, packages/time/package.json, packages/time/test/index.test.js, packages/webpack/get-config.js, packages/webpack/test/index.test.js, yarn.lock
before:
```
library/dist/index.js
Size limit: 85 KB
Size:       79.83 KB with all dependencies, minified and gzipped
Size limit: 85 KB
Size:       0 B   with all dependencies, minified and gzipped
Size limit: 100 KB
Size:       0 B    with all dependencies, minified and gzipped
```
after:
```
library/dist/index.js
Size limit: 85 KB
Size:       79.83 KB with all dependencies, minified and gzipped
File not found: library/dist/index2.js
Size limit: 85 KB
Size:       0 B   with all dependencies, minified and gzipped
File not found: public/packs-test/lite-*.js
Size limit: 100 KB
Size:       0 B    with all dependencies, minified and gzipped
```
=> Add information which file was not found

README.md
Closes https://github.com/ai/size-limit/issues/191
Not sure whether this explanation would fit anywhere nicely so I've added a new section
=> Add running time measurements note

packages/size-limit/create-help.js, packages/size-limit/create-reporter.js, packages/size-limit/get-config.js, packages/size-limit/parse-args.js, packages/size-limit/test/__snapshots__/create-reporter.test.js.snap, packages/size-limit/test/__snapshots__/run.test.js.snap, packages/size-limit/test/create-reporter.test.js, packages/size-limit/test/get-config.test.js
Looks like this in my color scheme:
Closes #202
=> Add --highlight-less flag // closes feature request #202

.gitignore, packages/size-limit/create-reporter.js, packages/size-limit/parse-args.js, packages/size-limit/run.js, packages/size-limit/test/__snapshots__/create-reporter.test.js.snap, packages/size-limit/test/__snapshots__/run.test.js.snap, packages/size-limit/test/create-reporter.test.js, packages/size-limit/test/run.test.js
=> Add flag --silent for silent mode

packages/size-limit/calc.js, packages/size-limit/create-reporter.js, packages/size-limit/run.js, packages/size-limit/test/__snapshots__/create-reporter.test.js.snap, packages/size-limit/test/__snapshots__/run.test.js.snap, packages/size-limit/test/run.test.js
=> fail on missed entries

packages/size-limit/package.json, packages/size-limit/run.js, packages/size-limit/test/run.test.js, yarn.lock
Hello!
Ora replacement by my own mico-spinner. #232
=> Ora replacement to mico-spinner

packages/size-limit/run.js
Hello! Really cool project!
But I think the watch mode needs some improvements. Right now it watches all js files in the current directory, excluding node_modules. So now it doesn't work for css, for example. And I think you can imagine how many unnecessary reruns there can be. So I made it watch all the files from config.checks. Not sure if using flatMap is ok for supported node versions though. I can replace it if needed.
Also, despite package.json being watched, changes there are not applied, so I removed it for now to avoid confusion. I'm going to make it apply package.json changes as a next step and I have some more improvements in my mind related to watch mode.
I'm just not sure if it's ok to do in a single PR or multiple. What do you think?
=> Improve watch mode

packages/size-limit/test/__snapshots__/run.test.js.snap, packages/webpack/get-config.js
This pr aim to fix this issue  https://github.com/webpack/webpack/issues/5087#issuecomment-542881719, and I found  [this commit](https://github.com/broerjuang/nx-next/commit/0bea2f258f16fd27628c5f5134d23f29b00b62ed) resolve my problem.
=> fix style-loader  can't resolve when using pnpm

README.md
=> docs: clarify how to use `plugins` manually

packages/preset-small-lib/README.md
preset-small-lib readme: webpack -> esbuild
=> preset-small-lib readme: webpack -> esbuild

packages/time/get-running-time.js
fixes https://github.com/ai/size-limit/issues/331
=> fix: remove react dependency and use unpkg link instead

README.md
https://github.com/ant-design/ant-design/pull/49536#issuecomment-2181973455
=> chore: Ant Design is using Size Limit

README.md
Improve documentation for npx usage
Closes #371
Added documentation about using Size Limit with npx while maintaining the plugin architecture requirements. The changes include:
1. Added "Flexible usage" as a key feature in the introduction bullet points
2. Created a new "Quick Start with npx" section at the beginning of the Usage section
3. Clearly documented the requirement for plugin installation
4. Provided practical examples of both installation and usage commands
Following the discussion in #371, this PR improves the documentation to better support users who want to use Size Limit with npx. While maintaining the tool's plugin architecture, we now provide clear guidance on how to use Size Limit with npx after installing the necessary plugins.
=> Improve documentation for npx usage

packages/size-limit/create-help.js, packages/size-limit/test/__snapshots__/run.test.js.snap
I keep forgetting the name of this flag, can we print it in the CLI help?
=> Add documentation for `--save-bundle` flag
